apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  labels:
    app: nginx
data:
  nginx.conf: |
    user       nobody;  ## Default: nobody
    worker_processes  5;  ## Default: 1
    worker_rlimit_nofile 8192;

    events {
      worker_connections  4096;  ## Default: 1024
    }

    http {
      server { # php/fastcgi
        listen       80;
        server_name  _;
        access_log   /dev/stdout;
        error_log    /dev/stdout;
        root         /var/www/html;
        index        index.htm index.html;
      }

      }
    
