apiVersion: apps/v1
kind: Deployment
metadata:
  name:  nginx-simple
  labels:
    name:  nginx-simple
spec:
  selector:
    matchLabels:
      name: nginx-simple
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name:  nginx-simple
    spec:
      containers:
      - image:  nginx:1.23.4-alpine
        name:  nginx-simple
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
          limits:
            cpu: "40m"
            memory: "128M"
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: 80
        #   initialDelaySeconds: 90
        #   timeoutSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: 80
        #   initialDelaySeconds: 30
        #   timeoutSeconds: 10
        ports:
        - containerPort:  80
          name:  nginx-simple
        volumeMounts:
        - mountPath: /etc/nginx/
          name: nginx-config
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config